# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: spanner-app
  name: spanner-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spanner-app
  template:
    metadata:
      labels:
        name: spanner-app
    spec:
      serviceAccountName: spanner-app
      containers:
      - image: asia.gcr.io/<project id>/spanner-app:v1
        name: spanner-app
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: <project id>
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
